export const BOOK_FETCH_START = "BOOK_FETCH_START";
export const BOOK_FETCH_IN_PROGRESS = "BOOK_FETCH_IN_PROGRESS";
export const BOOK_FETCH_SUCCESS = "BOOK_FETCH_SUCCESS";
export const BOOK_FETCH_ERROR = "BOOK_FETCH_ERROR";
